services:
  # ---------- PHP‑FPM -----------------
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./laravel:/var/www
    #  ↓ MySQL no longer required
    #depends_on:
    #  - db
    networks:
      - laravel

  # ---------- Nginx -------------------
  web:
    image: nginx:alpine
    container_name: laravel_web
    ports:
      - "8000:80"
    volumes:
      - ./laravel:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - laravel

# volumes:   # <— dbdata no longer needed
#   dbdata:

networks:
  laravel:
